default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  host: localhost
  username: postgres
  password: password # Make sure to replace with the actual password

development:
  <<: *default
  database: hello_app_dev
  username: postgres
  password: password

test:
  <<: *default
  database: hello_app_test
  username: postgres
  password: password

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
  pool: <%= ENV['DB_POOL'] || 5 %>
  database: hello_app_prod
  username: postgres
  password: password
