default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  host: localhost
  username: postgres
  password: password # Make sure to replace with the actual password

development:
  <<: *default
  database: weather_app_dev # Change the database name
  username: postgres
  password: password

test:
  <<: *default
  database: weather_app_test # Change the database name
  username: postgres
  password: password

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
  pool: <%= ENV['DB_POOL'] || 5 %>
  database: weather_app_prod # Change the database name
  username: postgres
  password: password